# Generated by Django 5.1.1 on 2024-09-18 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_summonsmodel_member'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonsmodel',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='summons', to='team.membermodel'),
            preserve_default=False,
        ),
    ]
