# Generated by Django 5.1.1 on 2024-09-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('project', '0002_alter_summonsmodel_member'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskHistory',
            new_name='TaskHistoryModel',
        ),
    ]
