# Generated by Django 5.1.1 on 2024-09-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_rename_taskhistory_taskhistorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistorymodel',
            name='progress',
            field=models.CharField(max_length=100),
        ),
    ]
