# Generated by Django 5.1.1 on 2024-09-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_taskhistorymodel_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistorymodel',
            name='task',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='taskhistorymodel',
            name='updated_by',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
